#group: edge
#dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  # helper wait_for function, usage: `wait_for 8080`
  - >
    function wait_for {
      export port=$1
      while [ "$(sudo lsof -t -i:${port} | wc -l)" == "0" ]; do sleep 1; done;
    }

  # helper stop_any function. usage: `stop_any 8080`
  - >
    function stop_any {
      export port=$1
      sudo kill $(sudo lsof -t -i:$port) | true
    }

  - sudo apt update

  # HTTPie
  - sudo apt install -y python-pip
  - sudo pip install httpie

  ## cURL
  #- sudo apt install -y curl jq libxml2-utils

  ## docker-compose
  #- sudo apt install -y python-pip curl jq libxml2-utils
  #- sudo pip install docker-compose
  #- sudo usermod -aG docker $(whoami)

  # kill whatever running on port
  - stop_any 8080

script:

  - bash mvnw clean package
  #- bash target/*jar &
  - java -jar target/*jar &
  - wait_for 8080
  - echo '{"query":"{ people { name } }"}' | http post :8080
  - echo '{"query":"{ people { id name } }"}' | http post :8080
  - stop_any 8080

  - bash gradlew clean build
  #- bash build/libs/*jar &
  - java -jar build/libs/*jar &
  - wait_for 8080
  - echo '{"query":"{ people { id name } }"}' | http post :8080
  - echo '{"query":"{ people { name } }"}' | http post :8080
  - stop_any 8080

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
