#group: edge
#dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:

  ## install docker-compose
  #- sudo apt update
  #- sudo apt install -y python-pip curl jq libxml2-utils
  #- sudo pip install docker-compose httpie
  #- sudo usermod -aG docker $(whoami)

  # kill whatever punning on postgres / rabbitmq port
  - sudo kill $(sudo lsof -t -i:8080) | true

script:
  - bash mvnw package
  - bash gradlew build

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
